name: cure
description: >-
  A library for Dart developers which contains some useful tools and extensions: Signalr, MessagePack, CRC, HTTP, EventSource, WebSocket, etc.
version: 0.1.0-nullsafety.0
homepage: https://github.com/yanshouwang/cure
publish_to: https://pub.dev

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ansicolor: ^2.0.0-nullsafety
  meta: ^1.3.0-nullsafety
  pedantic: ^1.10.0-nullsafety
  string_scanner: ^1.1.0-nullsafety
  tuple: ^2.0.0-nullsafety

dev_dependencies:
  build_runner: ^1.10.13
  mockito: ^5.0.0-nullsafety
  test: ^1.16.0-nullsafety
