name: cure
description: >-
  A library for Dart developers which contains some useful tools and extensions: Signalr, MessagePack, CRC, HTTP, EventSource, WebSocket, etc.
version: 0.0.4
homepage: https://github.com/yanshouwang/cure

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  pedantic: ^1.9.2
  string_scanner: ^1.0.5
  tuple: ^1.0.3

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3
